version: '3.8'
services:
  db:
    container_name: ${PG_HOST}
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${PG_PASSWORD}
      MYSQL_DATABASE: ${PG_DATABASE}
    ports:
      - "3306:3306" 
  app:
    image: node:14
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    command: bash -c "npm install && npm run dev"
    ports:
      - "4006:4006"
    depends_on:
      - db