name: Deploy using SSH password

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 192.3.55.121
          username: admin-elpaso  # o deployuser, si ese es el correcto
          password: ${{ secrets.SSH_PASS }}
          port: 22
          script: |
            cd /home/admin-elpaso/BACK_DelPaso
            git reset --hard
            git clean -fd
            git pull origin main
            npm ci
            npm run build
            pm2 restart back-elpaso || pm2 start dist/src/index.js --name back-elpaso

